# D-Gen | https://t.me/DisappearGen
param(
    [string]$BinDir,
    [string]$OutDir
)

$ErrorActionPreference = 'Stop'

$root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path

if (-not $BinDir) {
    $BinDir = Join-Path $root 'bin'
}

if (-not $OutDir) {
    $OutDir = Join-Path $root 'engine\src\nfq'
}

$inputs = @(
    @{ Id = 'QUIC_INIT_GOOGLE'; File = 'quic_initial_www_google_com.bin'; Var = 'DGEN_TPL_QUIC_INIT_GOOGLE_HEX' },
    @{ Id = 'TLS_CH_GOOGLE'; File = 'tls_clienthello_www_google_com.bin'; Var = 'DGEN_TPL_TLS_CH_GOOGLE_HEX' },
    @{ Id = 'TLS_CH_MAX_RU'; File = 'tls_clienthello_max_ru.bin'; Var = 'DGEN_TPL_TLS_CH_MAX_RU_HEX' },
    @{ Id = 'TLS_CH_4PDA'; File = 'tls_clienthello_4pda_to.bin'; Var = 'DGEN_TPL_TLS_CH_4PDA_HEX' }
)

function Get-HexLower([byte[]]$bytes) {
    $sb = New-Object System.Text.StringBuilder ($bytes.Length * 2)
    foreach ($b in $bytes) {
        [void]$sb.AppendFormat('{0:x2}', $b)
    }
    return $sb.ToString()
}

function Emit-CStringChunks([string]$full, [int]$chunkLen) {
    $chunks = @()
    for ($i = 0; $i -lt $full.Length; $i += $chunkLen) {
        $take = [Math]::Min($chunkLen, $full.Length - $i)
        $chunks += $full.Substring($i, $take)
    }
    return $chunks
}

function Emit-ConstLines([string]$var, [string]$full, [int]$chunkLen) {
    $lines = @()
    $lines += ("const char {0}[] =" -f $var)
    foreach ($ch in (Emit-CStringChunks -full $full -chunkLen $chunkLen)) {
        $lines += ('    "{0}"' -f $ch)
    }
    $lines += '    ;'
    return $lines
}

$headerPath = Join-Path $OutDir 'dgen_embedded_templates.h'
$implPath = Join-Path $OutDir 'dgen_embedded_templates.c'

$nl = [Environment]::NewLine
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

$h = @()
$h += '#pragma once'
$h += ''
$h += '// AUTO-GENERATED by utils\gen-embedded-templates.ps1. DO NOT EDIT.'
$h += '// Source inputs: .bin templates in bin/ (developer-only).'
$h += ''
foreach ($it in $inputs) {
    $h += ("extern const char {0}[];" -f $it.Var)
}

[System.IO.File]::WriteAllText($headerPath, (($h -join $nl) + $nl), $utf8NoBom)

$c = @()
$c += '#include "dgen_embedded_templates.h"'
$c += ''
$c += '// AUTO-GENERATED by utils\gen-embedded-templates.ps1. DO NOT EDIT.'
$c += ''

$chunkLen = 120

foreach ($it in $inputs) {
    $p = Join-Path $BinDir $it.File
    if (-not (Test-Path -LiteralPath $p)) {
        throw ("Missing template input: {0}" -f $p)
    }

    $bytes = [System.IO.File]::ReadAllBytes($p)
    $hex = '0x' + (Get-HexLower -bytes $bytes)

    $c += (Emit-ConstLines -var $it.Var -full $hex -chunkLen $chunkLen)
    $c += ''
}

[System.IO.File]::WriteAllText($implPath, (($c -join $nl) + $nl), $utf8NoBom)

Write-Host ("OK: wrote {0}" -f $headerPath)
Write-Host ("OK: wrote {0}" -f $implPath)
